# Generated by Django 4.1.1 on 2022-10-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_number", models.IntegerField(unique=True)),
                ("price_usd", models.DecimalField(decimal_places=6, max_digits=15)),
                ("delivery_date", models.DateField()),
                ("price_rub", models.DecimalField(decimal_places=6, max_digits=15)),
            ],
            options={
                "db_table": "orders",
                "managed": False,
            },
        ),
    ]
